### ISSUE TITLE
Unable to load native library: $PREFIX/libjava.so

### ISSUE THREAD

**Issue by jschueller** [conda-forge/r-rjava-feedstock#13]
hello,
I have a problem with a recipe that uses rjava, the error seems to be at the loading of java:
```** R
2020-02-29T10:39:05.2945622Z ** data
2020-02-29T10:39:05.2945893Z ** demo
2020-02-29T10:39:05.2946851Z ** byte-compile and prepare package for lazy loading
2020-02-29T10:39:05.3170192Z Error occurred during initialization of VM
2020-02-29T10:39:05.3171147Z Unable to load native library: $PREFIX/libjava.so: cannot open shared object file: No such file or directory
2020-02-29T10:39:06.8908236Z Traceback (most recent call last):
```

however, JAVA_HOME is set to PREFIX and everything looks fine when I call javareconf
I noticed that libjava.so is in PREFIX/jre/lib/amd64, so I tried to set JAVA_LD_LIBRARY_PATH and LD_LIBRARY_PATH and even copying these *.so to PREFIX but then I've got another java error.

could you help me figure this out ?

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=126561&view=logs&j=10bda42a-d420-5c28-a43f-bc4e66405e5c

**Comment by dpryan79** [comment]
The java version this is linked to needs to be restricted, that will presumably solve the problem.

**Comment by jschueller** [comment]
Where do you get that ? I see rjava pulls openjdk 8.

**Comment by dpryan79** [comment]
Hmm, maybe that's not the issue then. It at least used to be a problem that r-rjava wasn't pinned to any particular java release.

**Comment by dpryan79** [comment]
Maybe it's a `javareconf` issue then. At some point r-base has modified to disable always running `R CMD javareconf`, since that was causing issues when activating environments. Try adding that at the beginning of the `build.sh`.

**Comment by dpryan79** [comment]
Here's another package with a similar issue: https://github.com/conda-forge/r-xlsx-feedstock/pull/9

**Comment by jschueller** [comment]
it seems I get the same problem when adding the javareconf call:
```
JAVA_HOME        : $PREFIX
2020-03-01T08:40:12.2169376Z Java library path: $PREFIX/jre/lib/amd64/server
2020-03-01T08:40:12.2173440Z JNI cpp flags    : -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux
2020-03-01T08:40:12.2174211Z JNI linker flags : -L$(JAVA_HOME)/jre/lib/amd64/server -ljvm
2020-03-01T08:40:12.2176730Z Updating Java configuration in $PREFIX/lib/R
2020-03-01T08:40:12.2310708Z Done.
 ```

**Comment by hermidalc** [comment]
I'm having a similar issue but with the latest `r-rjava` itself. It used to work all the time out of the box after the `conda install` without any manual `R CMD javareconf` or other rJava and Java configuration hell (which used to make me want to bash my head in to trying to get it working before conda-forge `r-rjava` just make it happen).

I haven't used rJava in a little while so I don't know what broke it.  But I believe even a few months ago the latest `conda-forge` `r-rjava` was working without this error.

Now after installing it and running this test it throws a similar error to the OP.  It's got the path all wrong:

```R
> library(rJava)
> .jinit()
Error occurred during initialization of VM
Unable to load native library: /home/hermidalc/soft/miniconda3/envs/test-env/libjava.so: cannot open shared object file: No such file or directory
```

**Comment by hermidalc** [comment]
Found the problem.  There is something wrong with the latest `openjdk=8.0.192=h516909a_1004` and it's causing the issue.  Not sure what done wrong with that build.  It was built and uploaded end of January.  If you downgrade to the previous build `openjdk=8.0.192=h14c3975_1003` everything works again.

**Comment by jschueller** [comment]
thanks @hermidalc, moved to https://github.com/conda-forge/openjdk-feedstock/issues/66
