### ISSUE TITLE
Drop (non-existent) Arch builds again to enable R 4.0

### ISSUE THREAD

**Issue by xhochy** [conda-forge/r-rjava-feedstock#17]
Currently the R 4.0 migrator is not attempting to rebuild `r-rjava` as `openjdk=8` is not available for ppc64le. As there have never been successful builds for aarch64 or ppc64le either, I would suggest to drop them again from the matrix and just rebuild the existing successful builds for R 4.0.

@CJ-Wright briefly mentioned this yesterday in the core meeting and we sadly hadn't had the time to talk about it. Thus moving this here.

cc @conda-forge/r-rjava @conda-forge/arm-arch @beckermr

**Comment by beckermr** [comment]
LGTM!
