### ISSUE TITLE
Issue with openjdk>=9

### ISSUE THREAD

**Issue by npavlovikj** [conda-forge/r-rjava-feedstock#6]
Hi,

This recipe doesn't work with openjdk>=9: `library(rJava)` returns `libjvm.so: cannot open shared object file: No such file or directory`.
The reason is explained here, https://github.com/conda-forge/openjdk-feedstock/pull/34.
If I force openjdk to 8, then the package works fine. 
It will be nice if the recipe can be updated accordingly.
The same issue happens with r-rjava from the r channel as well.

Thank you,
Natasha

**Comment by dpryan79** [comment]
In #7 I have this pinned to a particular openjdk release (8.*). The issue is caused be different openjdk versions having libjvm.so in different places, which will obviously break all of the rpath stuff.

**Comment by izahn** [comment]
Is pinning to openjdk 8 still needed? OpenJDK8 getting pretty old, and some things (e.g., eclipse) no longer work with it. It looks like the original issues that prompted the pin to version 8 was closed in https://github.com/kivy/pyjnius/issues/304
